spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:school}?currentSchema=${DB_SCHEMA_NAME:student_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:310892}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
  flyway:
    enabled: true
    schemas:
      - ${DB_SCHEMA_NAME:student_db}
    baseline-on-migrate: true
    baseline-version: 1
  main:
    banner-mode: off
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    auto-startup: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  shell:
    interactive:
      enabled: false
